### ISSUE TITLE
Problem setting defaults values

### ISSUE THREAD

**Issue by pcriv** [maoueh/nugrant#12]
I tried setting this defaults on my vagrant file:

``` ruby
config.user.defaults = {
    "host" => {  
      "rails_server_port" => 3000,
      "apps_folder" => "../../rails-apps/" },
    "plugins" => {
      "vagrant_cachier" => {
        "enabled" => false
      }
    } 
  }
```

and my .vagrantuser has the following content:

```
host:
  rails_server_port:
  apps_folder: "../../rails-apps/"
plugins:
  vagrant_cachier:
    enabled: true
```

When i run vagrant (up/reload) i get the following error:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* Forwarded port definitions require a "host" and "guest" value
```

What am i doing wrong? 
I also tried removing the "rails_server_port" param from .vagrantuser file but i get an undefined param error.
