### ISSUE TITLE
Check if a key is defined in the .vagrantuser file

### ISSUE THREAD

**Issue by rodis** [maoueh/nugrant#15]
HI,

I was wondering if there is a way to check in the Vagrantfile, if a key is defined in the config.user object. For example, given a .vagrantuser file like this:

``` yaml
domain:
  memory: 2048
  cpus: 2
  nested: true
sync_nfs_folder:
  host_folder: "..."
  guest_folder: "..."
```

I would like to do something like this in the Vagrantfile

``` ruby
if config.user.has?('sync_nfs_folder')
  node.vm.synced_folder config.user.sync_nfs_folder.host_folder, config.user.sync_nfs_folder.guest_folder, nfs: true
end
```

I didn't find a way to do that, but I'm not a ruby programmer so this may be my fault.

Thanks
Rosario
