### ISSUE TITLE
Configuration file precedence/hierarchy

### ISSUE THREAD

**Issue by spul** [maoueh/nugrant#33]
Hi,

scenario is:

* Vagrantfile allows user custom configuration based on nugrant
* Vagrantfile should stay as simple as possible
* User should not be forced to configure all variables available

My understanding for the ``.vagrantuser`` file within the same directory as Vagrantfile would be to define default values IF a user does not configure those in his/her custom ``~/.vagrantuser``.  I'd favor something like:

```ruby
# Vagrantfile
...
if Vagrant.has_plugin?('nugrant')
  config_vm_box = config.user.vagrant.vm.box
  config_vm_box_check_update = config.user.vagrant.vm.box_check_update
else
  config_vm_box = 'ubuntu/trusty64'
  config_vm_box_check_update = false
end
...
config.vm.box = ENV['VAGRANT_BOXNAME'] || config_vm_box
config.vm.box_check_update = confg_vm_box_check_update
```

```yaml
# ~/.vagrantuser (note: this does not configure box update check
vagrant:
  vm:
    box: centos/7
```

```yaml
# .vagrantuser (within the same dir as Vagrantfile)
vagrant:
  vm:
    box: ubuntu/trusty64         # this SHOULD NOT win over ~/.vagrantuser -> centos/7
    box_check_update: false
```

My understanding would be to use ``.vagrantuser`` for sane defaults IF a user does not define some configuration variables, but not to overwrite user specific configuration (which this plugin is for).

My real issue is Vagrantfile getting complex if any nested YAML from .vagrantuser file needs to get sanitized for availability. afaik if there is a nested key referenced in Vagrantfile which is not configured in ``~/.vagrantuser``, ``vagrant up`` fails.

What do you think?
